name: Backend Pipline

on:
    push:
        branches: 
            - main

jobs:
    Unit-Test:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repo
              uses: actions/checkout@v6
            
            - name: Install Dep
              run: npm i

            - name: run unit Test
              run: npm run test

            

    Build-And-Push:
        runs-on: ubuntu-latest
        steps:
            - name: Clone Repo
              uses: actions/checkout@v6

            - name: build docker image
              run: docker build talel12/api-session15 .

            - name: check image
              run: docker images


    # Deployment